name: Parity Tests Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  parity-tests-windows:
    uses: ./.github/workflows/parity_test_base.yml
    with:
      platform_name: Windows
      runner: windows-latest
      test_command: .\build\native-release\tests\parity_tests.exe
